### Create report
POST http://localhost:3000/reports
Content-Type: application/json
    
{
    "make": "Ford",
    "model": "Mustang",
    "year": 1982,
    "mileage": 50000,
    "price": 20000,
    "lng": 45,
    "lat": 45
}

### Approve a report
PATCH http://localhost:3000/reports/11
Content-Type: application/json

{
    "approved": true
}

### Get an estimate for an exsiting report
GET http://localhost:3000/reports?make=Ford&model=Mustang&year=1981&mileage=10000&lat=45&lng=45





