### Create report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Mitsubishi",
    "model": "Lancer Evolution",
    "year": 2022,
    "mileage": 5000,
    "price": 25000,
    "lng": 0,
    "lat": 0
}

### Approve a report
PATCH http://localhost:3000/reports/10
Content-Type: application/json

{
    "approved": false
}

### Get an estimate for an exsiting report
GET http://localhost:3000/reports?make=toyota&model=camry&year=2020&mileage=10000&lat=0&lng=0





